# Generated by Django 3.2.2 on 2022-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='cover.jpg', upload_to='cover'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='avatar.jpg', upload_to='profile'),
        ),
    ]
