# Generated by Django 4.0.5 on 2022-07-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_cover_alter_profile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=56, null=True)),
                ('facebook', models.URLField(blank=True, max_length=56, null=True)),
                ('twitter', models.URLField(blank=True, max_length=56, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=56, null=True)),
            ],
        ),
    ]
