# Generated by Django 4.0.5 on 2022-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='github',
            field=models.URLField(blank=True, max_length=56, null=True),
        ),
    ]
