# Generated by Django 3.2.2 on 2022-05-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_favorites_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
